# Generated by Django 4.1.7 on 2023-05-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientedobanco',
            name='numero_telefone',
            field=models.CharField(max_length=20),
        ),
    ]
