# Generated by Django 4.2.1 on 2023-05-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('destinatarioCPF', models.IntegerField()),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.conta')),
            ],
        ),
    ]
