# Generated by Django 4.2.1 on 2023-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='fullName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
