# Generated by Django 4.2.1 on 2023-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_clientedobanco_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientedobanco',
            name='username',
        ),
        migrations.AddField(
            model_name='clientedobanco',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
