# Generated by Django 4.2.1 on 2023-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_fullname_transferencia_nomecompleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_parcelas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
