# Generated by Django 4.2.1 on 2023-05-21 23:53

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_clientedobanco_username_clientedobanco_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientedobanco',
            old_name='nome',
            new_name='nomeCompleto',
        ),
        migrations.AddField(
            model_name='clientedobanco',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
