# Generated by Django 4.2.1 on 2023-05-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_conta_saldo_alter_emprestimo_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao', models.CharField(choices=[('T', 'Transferência'), ('E', 'Empréstimo'), ('P', 'Pix')], default='E', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomeCompleto', models.CharField(max_length=255)),
                ('data', models.DateField(auto_now=True)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.conta')),
            ],
        ),
    ]
